before_script:
    - git clone https://github.com/syngan/vim-vimlint /tmp/vim-vimlint
    - git clone https://github.com/ynkdir/vim-vimlparser /tmp/vim-vimlparser

script:
  - sh /tmp/vim-vimlint/bin/vimlint.sh -l ~/.vim/bundle/vim-vimlint -p ~/.vim/bundle/vim-vimlparser -e EVL103=1 -e EVL102.l:_=1 autoload plugin
